apiVersion: apps/v1
kind: Deployment
metadata:
  name: rtest
  labels:
    app: rtest
  annotations:
    prometheus.io/port: "1323"
    prometheus.io/scrape: "true"
spec:
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  replicas: 10
  selector:
    matchLabels:
      app: rtest
  template:
    metadata:
      labels:
        app: rtest
    spec:
      containers:
      - name: rtest
        image: darron/connection-secret-example@sha256:f1f16a827c5887308a9c5d81e3cbc0cef9e404e3dc43d657ac257357d7ddcb89
        env:
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: rtest
              key: url
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rtest
              key: password
        - name: REDIS_CLIENT_USE_TLS
          valueFrom:
            secretKeyRef:
              name: rtest
              key: use_tls
        ports:
        - containerPort: 1323
        livenessProbe:
          httpGet:
            path: /healthz
            port: 1323
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          initialDelaySeconds: 3
          periodSeconds: 2
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 1
          httpGet:
            host:
            scheme: HTTP
            path: /healthz
            port: 1323
